# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/tighe/Desktop/redmasters/FPGA_Xilinx/Cores/Barris/pulser/pulser.cache/wt [current_project]
set_property parent.project_path /home/tighe/Desktop/redmasters/FPGA_Xilinx/Cores/Barris/pulser/pulser.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/tighe/Desktop/redmasters/FPGA_Xilinx/Cores/Barris/pulser/pulser.srcs/sources_1/new [current_project]
read_verilog -library xil_defaultlib /home/tighe/Desktop/redmasters/FPGA_Xilinx/Cores/Barris/pulser/pulser.srcs/sources_1/new/pulser.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top pulser -part xc7z010clg400-1


write_checkpoint -force -noxdef pulser.dcp

catch { report_utilization -file pulser_utilization_synth.rpt -pb pulser_utilization_synth.pb }
