# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cfg/ports.xdc

# XDC: imports/cfg/clocks.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_ps_0_0/system_ps_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0}]

# IP: bd/system/ip/system_rst_0_0/system_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0}]

# IP: bd/system/ip/system_cfg_0_0/system_cfg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_cfg_0_0 || ORIG_REF_NAME==system_cfg_0_0}]

# IP: bd/system/ip/system_ps_0_axi_periph_0/system_ps_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps_0_axi_periph_0 || ORIG_REF_NAME==system_ps_0_axi_periph_0}]

# IP: bd/system/ip/system_const_3_0/system_const_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_const_3_0 || ORIG_REF_NAME==system_const_3_0}]

# IP: bd/system/ip/system_sts_0_0/system_sts_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sts_0_0 || ORIG_REF_NAME==system_sts_0_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_axis_ram_writer_0_0/system_axis_ram_writer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_ram_writer_0_0 || ORIG_REF_NAME==system_axis_ram_writer_0_0}]

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0}]

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0}]

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0}]

# IP: bd/system/ip/system_util_ds_buf_0_1/system_util_ds_buf_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_util_ds_buf_0_1 || ORIG_REF_NAME==system_util_ds_buf_0_1}]

# IP: bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_1 || ORIG_REF_NAME==system_clk_wiz_0_1}]

# IP: bd/system/ip/system_xlslice_0_0/system_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_0 || ORIG_REF_NAME==system_xlslice_0_0}]

# IP: bd/system/ip/system_axis_dwidth_converter_0_0/system_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_dwidth_converter_0_0 || ORIG_REF_NAME==system_axis_dwidth_converter_0_0}]

# IP: bd/system/ip/system_axis_decimator_0_0/system_axis_decimator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_decimator_0_0 || ORIG_REF_NAME==system_axis_decimator_0_0}]

# IP: bd/system/ip/system_axis_decimator_0_1/system_axis_decimator_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_decimator_0_1 || ORIG_REF_NAME==system_axis_decimator_0_1}]

# IP: bd/system/ip/system_axis_dwidth_converter_0_1/system_axis_dwidth_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_dwidth_converter_0_1 || ORIG_REF_NAME==system_axis_dwidth_converter_0_1}]

# IP: bd/system/ip/system_ch_a_writer_0/system_ch_a_writer_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ch_a_writer_0 || ORIG_REF_NAME==system_ch_a_writer_0}]

# IP: bd/system/ip/system_ram_a_address_0/system_ram_a_address_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ram_a_address_0 || ORIG_REF_NAME==system_ram_a_address_0}]

# IP: bd/system/ip/system_sts_a_channel_0/system_sts_a_channel_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_sts_a_channel_0 || ORIG_REF_NAME==system_sts_a_channel_0}]

# IP: bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dds_compiler_0_0 || ORIG_REF_NAME==system_dds_compiler_0_0}]

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0}]

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}]

# IP: bd/system/ip/system_axi_cfg_register_0_0/system_axi_cfg_register_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cfg_register_0_0 || ORIG_REF_NAME==system_axi_cfg_register_0_0}]

# IP: bd/system/ip/system_axis_constant_0_0/system_axis_constant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_constant_0_0 || ORIG_REF_NAME==system_axis_constant_0_0}]

# IP: bd/system/ip/system_exp_interface_0_0/system_exp_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_exp_interface_0_0 || ORIG_REF_NAME==system_exp_interface_0_0}]

# IP: bd/system/ip/system_axi_cfg_register_0_1/system_axi_cfg_register_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cfg_register_0_1 || ORIG_REF_NAME==system_axi_cfg_register_0_1}]

# IP: bd/system/ip/system_exp_interface_0_1/system_exp_interface_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_exp_interface_0_1 || ORIG_REF_NAME==system_exp_interface_0_1}]

# IP: bd/system/ip/system_xlslice_2_0/system_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_2_0 || ORIG_REF_NAME==system_xlslice_2_0}]

# IP: bd/system/ip/system_gpio_n_lower_0/system_gpio_n_lower_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_gpio_n_lower_0 || ORIG_REF_NAME==system_gpio_n_lower_0}]

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0}]

# IP: bd/system/ip/system_axi_cfg_register_0_2/system_axi_cfg_register_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_cfg_register_0_2 || ORIG_REF_NAME==system_axi_cfg_register_0_2}]

# IP: bd/system/ip/system_axis_constant_1_0/system_axis_constant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_constant_1_0 || ORIG_REF_NAME==system_axis_constant_1_0}]

# IP: bd/system/ip/system_synthesizer_reference_0/system_synthesizer_reference_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_synthesizer_reference_0 || ORIG_REF_NAME==system_synthesizer_reference_0}]

# IP: bd/system/ip/system_axis_combiner_0_0/system_axis_combiner_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_combiner_0_0 || ORIG_REF_NAME==system_axis_combiner_0_0}]

# IP: bd/system/ip/system_axis_constant_0_1/system_axis_constant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_constant_0_1 || ORIG_REF_NAME==system_axis_constant_0_1}]

# IP: bd/system/ip/system_frequency_divider_0_0/system_frequency_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_frequency_divider_0_0 || ORIG_REF_NAME==system_frequency_divider_0_0}]

# IP: bd/system/ip/system_xlslice_0_4/system_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlslice_0_4 || ORIG_REF_NAME==system_xlslice_0_4}]

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0}]

# IP: bd/system/ip/system_xlconstant_0_1/system_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_1 || ORIG_REF_NAME==system_xlconstant_0_1}]

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0}]

# XDC: bd/system/ip/system_ps_0_0/system_ps_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_ps_0_0 || ORIG_REF_NAME==system_ps_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_rst_0_0/system_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_0_0/system_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_0_0 || ORIG_REF_NAME==system_rst_0_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_rst_0_0/system_rst_0_0_ooc.xdc

# XDC: bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc

# XDC: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_util_ds_buf_0_1/system_util_ds_buf_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ds_buf_0_1 || ORIG_REF_NAME==system_util_ds_buf_0_1}] {/U0 }]/U0 ]]

# XDC: bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_1 || ORIG_REF_NAME==system_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_1 || ORIG_REF_NAME==system_clk_wiz_0_1}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_1_ooc.xdc

# XDC: bd/system/ip/system_axis_dwidth_converter_0_0/system_axis_dwidth_converter_0_0_ooc.xdc

# XDC: bd/system/ip/system_axis_dwidth_converter_0_1/system_axis_dwidth_converter_0_1_ooc.xdc

# XDC: bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0_ooc.xdc

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: bd/system/ip/system_synthesizer_reference_0/system_synthesizer_reference_0_ooc.xdc

# XDC: bd/system/ip/system_axis_combiner_0_0/system_axis_combiner_0_0_ooc.xdc

# XDC: bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
