# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.cache/wt [current_project]
set_property parent.project_path /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/darryn/Git/other/redmasters/FPGA_Xilinx/Cores/Barris/StaleBuffer/stale_buffer_1.0
  /home/darryn/Git/other/redmasters/FPGA_Xilinx/Cores
} [current_project]
set_property verilog_define TOOL_VIVADO [current_fileset]
add_files /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_ps_0_0/system_ps_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_rst_0_0/system_rst_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_util_ds_buf_0_1/system_util_ds_buf_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_axis_dwidth_converter_0_0/system_axis_dwidth_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_axis_dwidth_converter_0_1/system_axis_dwidth_converter_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib {
  /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/new/exp_interface.v
  /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/sources_1/bd/system/hdl/system_wrapper.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/constrs_1/imports/cfg/ports.xdc
set_property used_in_implementation false [get_files /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/constrs_1/imports/cfg/ports.xdc]

read_xdc /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/constrs_1/imports/cfg/clocks.xdc
set_property used_in_implementation false [get_files /home/darryn/Git/milosar-fpga/adc_writer_ram/adc_writer_ram.srcs/constrs_1/imports/cfg/clocks.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z010clg400-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


write_checkpoint -force -noxdef system_wrapper.dcp

catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
