webtalk_init -webtalk_dir /home/tighe/Desktop/redmasters/FPGA_Xilinx/Cores/Barris/pri_trigger/pri_trigger.sim/sim_1/behav/xsim.dir/pri_trigger_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Dec 10 20:15:41 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1577090" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "178739136_178739138_210553786_049" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "79a6b32b-c238-4636-965d-c0b5d1b012bc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6b12c5ae88de4e0db219c7ff6f815ef5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.10" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5 CPU       M 460  @ 2.53GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1333.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "135772_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1288712572 -regid "178739136_178739138_210553786_049" -xml /home/tighe/Desktop/redmasters/FPGA_Xilinx/Cores/Barris/pri_trigger/pri_trigger.sim/sim_1/behav/xsim.dir/pri_trigger_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/tighe/Desktop/redmasters/FPGA_Xilinx/Cores/Barris/pri_trigger/pri_trigger.sim/sim_1/behav/xsim.dir/pri_trigger_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/tighe/Desktop/redmasters/FPGA_Xilinx/Cores/Barris/pri_trigger/pri_trigger.sim/sim_1/behav/xsim.dir/pri_trigger_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
